---
max_files: 0
include:
  - '*.gemspec'
  - 'Rakefile'
  - 'examples/**/*.rb'
  - 'lib/**/*.rb'
  - 'test/delivery_five_post_client/resource_namespaces.rb'
  - 'test/delivery_five_post_client/test_helper.rb'
exclude:
  - 'rbi/**/*'
