module DeliveryFivePostClient
  module Models
    module API
      module V1
        type execution_status =
          :CREATED
          | :RECEIVED
          | :RECEIVED_IN_DROP
          | :RECEIVED_IN_STORE
          | :RECEIVED_IN_TRANSIT_WAREHOUSE
          | :SHIPPED
          | :IN_TRANSIT
          | :READY_TO_RECEIVE
          | :DELIVERED
          | :RETURNED
          | :REJECTED
          | :CANCELLED
          | :LOST
          | :UNCLAIMED

        module ExecutionStatus
          extend DeliveryFivePostClient::Internal::Type::Enum

          CREATED: :CREATED
          RECEIVED: :RECEIVED
          RECEIVED_IN_DROP: :RECEIVED_IN_DROP
          RECEIVED_IN_STORE: :RECEIVED_IN_STORE
          RECEIVED_IN_TRANSIT_WAREHOUSE: :RECEIVED_IN_TRANSIT_WAREHOUSE
          SHIPPED: :SHIPPED
          IN_TRANSIT: :IN_TRANSIT
          READY_TO_RECEIVE: :READY_TO_RECEIVE
          DELIVERED: :DELIVERED
          RETURNED: :RETURNED
          REJECTED: :REJECTED
          CANCELLED: :CANCELLED
          LOST: :LOST
          UNCLAIMED: :UNCLAIMED

          def self?.values: -> ::Array[DeliveryFivePostClient::Models::API::V1::execution_status]
        end
      end
    end
  end
end
