module DeliveryFivePostClient
  module Models
    module API
      module V1
        module Partners
          module Tasks
            module Report
              type avd_create_response = { task_id: String }

              class AvdCreateResponse < DeliveryFivePostClient::Internal::Type::BaseModel
                attr_accessor task_id: String

                def initialize: (task_id: String) -> void

                def to_hash: -> { task_id: String }
              end
            end
          end
        end
      end
    end
  end
end
