module DeliveryFivePostClient
  module Resources
    class API
      class V1
        class Partners
          class ExtendStorageDays
            def extend_storage_days: (
              days: Integer,
              order_id: String,
              ?request_options: DeliveryFivePostClient::request_opts
            ) -> DeliveryFivePostClient::Models::API::V1::Partners::ExtendStorageDayExtendStorageDaysResponse

            def status: (
              task_id: String,
              ?request_options: DeliveryFivePostClient::request_opts
            ) -> DeliveryFivePostClient::API::V1::Partners::TaskStatusResponse

            def initialize: (client: DeliveryFivePostClient::Client) -> void
          end
        end
      end
    end
  end
end
