module DeliveryFivePostClient
  module Models
    module API
      module V2
        module Points
          type sl_get_c2c_delivery_terms_params =
            { from_location_id: String, to_location_id: String }
            & DeliveryFivePostClient::Internal::Type::request_parameters

          class SlGetC2cDeliveryTermsParams < DeliveryFivePostClient::Internal::Type::BaseModel
            extend DeliveryFivePostClient::Internal::Type::RequestParameters::Converter
            include DeliveryFivePostClient::Internal::Type::RequestParameters

            attr_accessor from_location_id: String

            attr_accessor to_location_id: String

            def initialize: (
              from_location_id: String,
              to_location_id: String,
              ?request_options: DeliveryFivePostClient::request_opts
            ) -> void

            def to_hash: -> {
              from_location_id: String,
              to_location_id: String,
              request_options: DeliveryFivePostClient::RequestOptions
            }
          end
        end
      end
    end
  end
end
