module DeliveryFivePostClient
  module Models
    module API
      module V1
        module Partners
          type extend_storage_day_extend_storage_days_params =
            { days: Integer, order_id: String }
            & DeliveryFivePostClient::Internal::Type::request_parameters

          class ExtendStorageDayExtendStorageDaysParams < DeliveryFivePostClient::Internal::Type::BaseModel
            extend DeliveryFivePostClient::Internal::Type::RequestParameters::Converter
            include DeliveryFivePostClient::Internal::Type::RequestParameters

            attr_accessor days: Integer

            attr_accessor order_id: String

            def initialize: (
              days: Integer,
              order_id: String,
              ?request_options: DeliveryFivePostClient::request_opts
            ) -> void

            def to_hash: -> {
              days: Integer,
              order_id: String,
              request_options: DeliveryFivePostClient::RequestOptions
            }
          end
        end
      end
    end
  end
end
