module DeliveryFivePostClient
  module Models
    module API
      module V1
        module Partners
          type warehouse_retrieve_params =
            {  } & DeliveryFivePostClient::Internal::Type::request_parameters

          class WarehouseRetrieveParams < DeliveryFivePostClient::Internal::Type::BaseModel
            extend DeliveryFivePostClient::Internal::Type::RequestParameters::Converter
            include DeliveryFivePostClient::Internal::Type::RequestParameters

            def initialize: (
              ?request_options: DeliveryFivePostClient::request_opts
            ) -> void

            def to_hash: -> {
              request_options: DeliveryFivePostClient::RequestOptions
            }
          end
        end
      end
    end
  end
end
