module DeliveryFivePostClient
  module Models
    module API
      module V1
        module Partners
          type warehouse_retrieve_params =
            { id: String }
            & DeliveryFivePostClient::Internal::Type::request_parameters

          class WarehouseRetrieveParams < DeliveryFivePostClient::Internal::Type::BaseModel
            extend DeliveryFivePostClient::Internal::Type::RequestParameters::Converter
            include DeliveryFivePostClient::Internal::Type::RequestParameters

            attr_accessor id: String

            def initialize: (
              id: String,
              ?request_options: DeliveryFivePostClient::request_opts
            ) -> void

            def to_hash: -> {
              id: String,
              request_options: DeliveryFivePostClient::RequestOptions
            }
          end
        end
      end
    end
  end
end
