module DeliveryFivePostClient
  module Internal
    module Type
      type request_parameters =
        { request_options: DeliveryFivePostClient::request_opts }

      module RequestParameters
        attr_reader request_options: DeliveryFivePostClient::request_opts

        def request_options=: (
          DeliveryFivePostClient::request_opts
        ) -> DeliveryFivePostClient::request_opts

        module Converter
          def dump_request: (top params) -> [top, ::Hash[Symbol, top]]
        end
      end
    end
  end
end
