module DeliveryFivePostClient
  module Models
    module API
      module V1
        module Partners
          module Orders
            type cargo_created_info =
              { barcode: String, cargo_id: String, sender_cargo_id: String }

            class CargoCreatedInfo < DeliveryFivePostClient::Internal::Type::BaseModel
              attr_accessor barcode: String

              attr_accessor cargo_id: String

              attr_accessor sender_cargo_id: String

              def initialize: (
                barcode: String,
                cargo_id: String,
                sender_cargo_id: String
              ) -> void

              def to_hash: -> {
                barcode: String,
                cargo_id: String,
                sender_cargo_id: String
              }
            end
          end
        end
      end
    end
  end
end
